CREATE TABLE IF NOT EXISTS USER_ACCESS(
	userId VARCHAR(100) NOT NULL,
	url VARCHAR(1024) NOT NULL,
	ip VARCHAR(64),
	prot VARCHAR(8),
	onLineTime TIMESTAMP,
	offLineTime TIMESTAMP
	CONSTRAINT pk PRIMARY KEY (userId,url)
);
